### ISSUE TITLE
End of period is inclusive?

### ISSUE THREAD

**Issue by robations** [smhg/date-period#4]
Firstly thanks for this component : ) I notice there is a difference from the PHP DatePeriod class in that the end date in PHP is exclusive, but in this class/function it is inclusive. If compatibility with PHP is important then might be worth either changing the behaviour, or noting this in the documentation. (I'm porting a library from PHP to TypeScript so I got hit by this.)

http://php.net/manual/en/dateperiod.construct.php (see comments for description of exclusive behaviour)

**Comment by smhg** [comment]
Thank you for your feedback! I'll have a look at this right away.
I guess I'm only using it with a number of recurrences or an ISO string. In which case it acts the same as the PHP version.

**Comment by robations** [comment]
Awesome.

**Comment by smhg** [comment]
And 0.3.0 is now also on npm (forgot about that yesterday).
