### ISSUE TITLE
Missing dist

### ISSUE THREAD

**Issue by joshuataylor** [smhg/date-period#6]
Missing dist for easier download.

**Comment by smhg** [comment]
You mean for manual installation? (it is included in npm)

**Comment by joshuataylor** [comment]
For installing via github, for "fly by" testers. I grabbed from npm (I built it using `npm install`), however for other javascript libraries you can just grab the 'full' file.

**Comment by smhg** [comment]
You're right. I've put the `dist` directory in git.
