### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed (in tests only)

### ISSUE THREAD

**Issue by n3ssi3** [smhg/date-period#7]
Hey there,

When I run my Tests I get following error:

```
Using Jest CLI v0.10.0, jasmine2
 FAIL  react/components/layout/__tests__/Wrapper-tests.js (5.358s)
● Wrapper › it test not implemented
  - Error: only one instance of babel-polyfill is allowed
        at Object.<anonymous> (node_modules/babel-polyfill/lib/index.js:12:9)
        at Object.<anonymous> (node_modules/date-period/dist/period.js:18:1)
        at Object.<anonymous> (react/utils/ChartsUtils.jsx:9:55)
```
Do you have an idea why this is?

My versions are : 
date-period@1.1.2
babel-polyfill@6.9.1

**Comment by smhg** [comment]
Which version of NPM are you using? 2 or 3?

**Comment by n3ssi3** [comment]
npm version 3.3.12

**Comment by smhg** [comment]
Can you test it with the latest version? Remove node_modules and reinstall just to be sure.
It might be something different, but there were changes and fixes to peerDependencies in version 3. You never know.

**Comment by n3ssi3** [comment]
Thanks updateing helped :)

**Comment by smhg** [comment]
Thanks, good to hear it's fixed!
